## 网络节点stop
tensorflow中有一个计算梯度的函数tf.gradients(ys, xs)，要注意的是，xs中的x必须要与ys相关，不相关的话，会报错。  
代码中定义了两个变量w1， w2， 但res只与w1相关  
可见，一个节点被 stop之后，这个节点上的梯度，就无法再向前BP了。由于w1变量的梯度只能来自a节点，所以，计算梯度返回的是None。  

In [1]:
import tensorflow as tf  
  
w1 = tf.Variable(2.0)  
w2 = tf.Variable(2.0)  
  
a = tf.multiply(w1, 3.0)  
a_stoped = tf.stop_gradient(a)  
  
# b=w1*3.0*w2  
b = tf.multiply(a_stoped, w2)  
gradients = tf.gradients(b, xs=[w1, w2])  
print(gradients)  

[None, <tf.Tensor 'gradients/Mul_1_grad/Reshape_1:0' shape=() dtype=float32>]


## Tensor 并不保存值，只是对结果的引用
保存了3个属性：name, shape, type  
add:0 表示为该节点的第一个输出  
shape 表示输出为1维数组，长度为4  
type 变量类型在创建之后不可改变  

In [4]:
import tensorflow as tf 
a = tf.constant([1, 2, 4 ,5], name = "a")
b = tf.constant([2, 3, 4 ,5], name = "b")
result = tf.add(a,b,name = "add")
print (result)

Tensor("add_1:0", shape=(4,), dtype=int32)


## Tensor的取值

In [9]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    #sess.run(result)
    print (result.eval())
    #print (sess.run(result))

[ 3  5  8 10]


## tf.InteractiveSession 直接将会话注册为默认会话

In [10]:
sess = tf.InteractiveSession()
print (result.eval())
sess.close()

[ 3  5  8 10]


In [17]:
X = tf.Variable(tf.truncated_normal([5,3],stddev=2))
W = tf.Variable(tf.fill([3,3],9.0),dtype = tf.float32)
h = tf.matmul(X,W)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print (h.eval())


[[-15.35807  -15.35807  -15.35807 ]
 [ 62.615593  62.615593  62.615593]
 [-41.004803 -41.004803 -41.004803]
 [ -9.809562  -9.809562  -9.809562]
 [ 22.583532  22.583532  22.583532]]


In [18]:
print (X)

<tf.Variable 'Variable_10:0' shape=(5, 3) dtype=float32_ref>


In [19]:
a = tf.constant([1, 2, 4 ,5], name = "a")
print (a)
b = tf.constant([[1, 2, 4 ,5]], name = "b")
print (b)

Tensor("a_2:0", shape=(4,), dtype=int32)
Tensor("b_2:0", shape=(1, 4), dtype=int32)
